### PR TITLE
Feature Calculator UI-Improvements

### PR DESCRIPTION
**Pull request by tibuch**
I did some general UI improvements.
* [x] Remove hardcoded sizes
* [x] Add overlapping label filter
* [x] Add customized input harvester for the auto-generated featureset panels
* [ ] Beautiful featureset description
* [ ] Select all features from featureset button
* [ ] Overlapping Features should not end with `;`

### CODE REVIEW

**Comment by dietzc** [comment]
see https://tech.knime.org/forum/knime-image-processing/featur-calculator-bug#comment-41943

**Comment by gab1one** [comment]
https://github.com/knime-ip/knip/issues/318

**Comment by dietzc** [comment]
@tibuch can we at least fix/merge what's already there?

**Comment by tibuch** [comment]
@gab1one  I got the following warning:
Access restriction: The type 'MigLayout' is not API (restriction on required library '.../workspace/.metadata/.plugins/org.eclipse.pde.core/.external_libraries/miglayout_3.7.4.201606281419/miglayout-3.7.4.jar')

**Comment by dietzc** [comment]
update your sdk ;-)

**Pull request merged**
