### PR TITLE
add replace transparent values with functionality.

### PR DESCRIPTION
**Pull request by seebacherd**
transparent values (alpha values = 255) can now be replaced with a customizable value.

see issue #93 .

### CODE REVIEW

**Comment by dietzc** [comment]
did you add a test-flow?

**Comment by seebacherd** [comment]
Nope, didn't really know how I should write a test workflow for that kind of functionality.

**Comment by dietzc** [comment]
Would be great if you could cover _any_ new functionality with a test-flow. It's easier to do it directly, than doing it afterwards.

Thanks!

**Comment by dietzc** [comment]
One more comment: I think the old workflow won't work with these changes, too (as you added/modified existing settings). So maybe we have to deprecate the old one?!

**Comment by seebacherd** [comment]
Nope the old workflow still works, we didn't change any existing settings. I've only added a new one which is no problem.

**Pull request merged**
