### PR TITLE
Update EclipseAnnotator.launch

### LINKED ISSUE #319: Feature Calculator (BETA): No compatible service: org.knime.knip.features.FeatureService
Hello together,

I'm trying to get KNIP running on Windows 10. I imported the projects knip, knip-sdk-setup and knip-scijava (master branch on everything). I'm using the knip-sdk-nightly-dev.target where I selected everything from https://community.knime.org/download/knip-externals-trunk, and the things I needed from https://update.knime.org/analytics-platform/3.1/ and http://update.knime.org/server/4.2.

Everything appears to work, the KNIP nodes like Image Reader etc. are running fine, but the Feature Calculator (Beta) throws an IllegalArgumentException when I try to connect it with other nodes with the message: No compatible service: org.knime.knip.features.FeatureService. I can open the dialog afterwards, but it appears to be broken, I can't add any FeatureSets.

I've included the full StackStrace of the Exception:

`
java.lang.IllegalArgumentException: No compatible service: org.knime.knip.features.FeatureService
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:243)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:194)
	at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:170)
	at org.scijava.Context.<init>(Context.java:278)
	at org.scijava.Context.<init>(Context.java:234)
	at org.knime.knip.features.FeaturesGateway.<init>(FeaturesGateway.java:85)
	at org.knime.knip.features.FeaturesGateway.getInstance(FeaturesGateway.java:92)
	at org.knime.knip.features.FeaturesGateway.fs(FeaturesGateway.java:105)
	at org.knime.knip.features.node.FeatureCalculatorModel.configure(FeatureCalculatorModel.java:228)
	at org.knime.core.node.NodeModel.configure(NodeModel.java:1088)
	at org.knime.core.node.NodeModel.configureModel(NodeModel.java:1037)
	at org.knime.core.node.Node.invokeNodeModelConfigure(Node.java:1815)
	at org.knime.core.node.Node.configure(Node.java:1751)
	at org.knime.core.node.workflow.NativeNodeContainer.performConfigure(NativeNodeContainer.java:527)
	at org.knime.core.node.workflow.SingleNodeContainer.callNodeConfigure(SingleNodeContainer.java:292)
	at org.knime.core.node.workflow.SingleNodeContainer.configure(SingleNodeContainer.java:177)
	at org.knime.core.node.workflow.WorkflowManager.configureSingleNodeContainer(WorkflowManager.java:5884)
	at org.knime.core.node.workflow.WorkflowManager.postLoad(WorkflowManager.java:7800)
	at org.knime.core.node.workflow.WorkflowManager.loadContent(WorkflowManager.java:7637)
	at org.knime.core.node.workflow.WorkflowManager.postLoad(WorkflowManager.java:7763)
	at org.knime.core.node.workflow.WorkflowManager.loadContent(WorkflowManager.java:7637)
	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7589)
	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7513)
	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7486)
	at org.knime.core.node.workflow.WorkflowManager.loadProject(WorkflowManager.java:7338)
	at org.knime.workbench.editor2.LoadWorkflowRunnable.run(LoadWorkflowRunnable.java:154)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
`

### PR DESCRIPTION
**Pull request by seebacherd**
Put the classpath variable between quotes, didn't work on Windows 10 otherwise (or maybe it didn't work because there is a whitespace in my username), anyhow this fixes #319.

### CODE REVIEW

**Comment by Squareys** [comment]
Yes, this is a whitespace problem. I fixed it in most other projects, but seemed to have missed this one.
You may give git the email address associated with your github account so that it can recognize the commit was yours. You can then [change the author of the commit](http://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit) respectively.

**Comment by seebacherd** [comment]
Okay, commit should be fine now

**Comment by Squareys** [comment]
Awesome :+1: 

@dietzc This looks great to me.

**Comment by dietzc** [comment]
thanks @seebacherd. However, I can't merge external PRs in KNIP. @Squareys can you redo this work and commit it?

**Comment by Squareys** [comment]
@dietzc Is this a license issue?

**Pull request closed without merging**
