### PR TITLE
New Image Reader

### PR DESCRIPTION
**Pull request by seebacherd**
Splitted the old image reader into two new ones. One which only reads files which are selected in the dialog and a second one which only reads files from an input table. Also cleaned up the code a little.

Testworkflow was uploaded to 3.0 with the name "KNIME_testing_ImageReader2"

@dietzc  please review and pull, thanks.

### CODE REVIEW

**Comment by dietzc** [comment]
did you test the streaming capabilities and upload a testflow to 3.0?

**Comment by DanielSeebacher** [comment]
Yes, I tested the streaming capabilities. Its already included in the 3.0 workflow.

screenshot_2015-09-01_12-25-15

**Comment by maierl** [comment]
the old image reader didn't support the "from-to variable" feature #146. will the new image reader support that?

**Comment by DanielSeebacher** [comment]
Yes, the new image reader nodes will support that feature.

**Comment by dietzc** [comment]
are there any other issue related to the image reader we could solve before we merge @DanielSeebacher & @gab1one?

**Comment by DanielSeebacher** [comment]
@dietzc the issues #79 and #135 are still open. We could fix them before the release, if it's possible and reasonable.

Also we could check if some other essential functionality is missing. @maierl maybe you can think of something? I'm also asking the other KNIP contributors tomorrow.

**Comment by dietzc** [comment]
@seebacherd please resolve #79 (certainly advanced and default is: auto-detect) and #135. then I will test. additionally, could you please add more test-cases to test the individual functions (especially all advanced settings) individually?

**Comment by dietzc** [comment]
@seebacherd two more things which came to my mind: please make sure that `knime://` paths are supported and maybe you can use the KNIME extension point which supports drag&drop of files into the KNIME workbench (if the extension of the file is supported). If you have questions about this you can ask the KNIME guys (Thorsten or Peter) if they are around.

**Comment by seebacherd** [comment]
@dietzc KNIME paths are supported, I'm using the org.knime.core.util.FileUtil to resolve paths. I also added drag&drop functionality (was really easy), but I'm currently only able to allow one single file. I'm checking if I can support list of files.

**Comment by dietzc** [comment]
Awesome. Have KNIME paths been supported before? Can you double-check?

**Comment by seebacherd** [comment]
Yes KNIME paths were already supported. The ReadFileImgTable also used the FileUtil.

**Comment by seebacherd** [comment]
Thanks for the input @dietzc. I've added all suffixes which are supported by SCIFIO to the plugin.xml in b03eed192277a96d6b3c031fc6485c3a660c2e90.

**Comment by seebacherd** [comment]
Puh, that is a really really difficult question. Currently I wouldn't even know where to start. We need to periodically check if there are suffixes supported by SCIFIO which aren't in the plugin.xml. Maybe with an additional Builder, something like our EclipseHelper?

Besides that, supporting multiple files could take some more time. Currently the Drag&Drop mechanism of KNIME only supports single files. Maybe I could add this functionality, but I need to be sure that all existing KNIME nodes which rely on the Drag&Drop mechanism still work afterwards. I'm not sure I have enough time to add this for the 1.4.0 release.

**Comment by dietzc** [comment]
Hm. Maybe we can postpone both issues until we get the chance to discuss the problems with the KNIME core team, as these problems seem to be on their side?

**Comment by seebacherd** [comment]
I wholeheartedly agree. The second issue is completely on the KNIME side. The only change from our side would be to exchange the line ```m_files.setStringArrayValue(new String[] { context.getUrl().getPath().toString() });``` with  ```m_files.setStringArrayValue(context.getURLS());```.

**Comment by dietzc** [comment]
I will contact them and CC you. Thanks!

**Comment by dietzc** [comment]
* [ ] Allow selection of only parts of an image series

**Comment by seebacherd** [comment]
fixed streaming for all ValueToCellNodes and removed too common file formats. Next Task -> allow subset selection.

**Comment by dietzc** [comment]
great! thanks! please close all related issues which are resolved!

**Pull request merged**
