### PR TITLE
change subset selection model from storing ints[] to storing strings

### PR DESCRIPTION
**Pull request by seebacherd**
this pull request changes the way the subset selection model stores its selection. before the subset selection model stored the selected indices in an int array. now the subset selection stores its indices as a string. this allows for easy modification of the selected indices with flow variables as request in #146 .

### CODE REVIEW

**Comment by dietzc** [comment]
did you test backwards compatibility (loading a stored node with the recent changed in implementation)?

**Comment by seebacherd** [comment]
This pull request would break backwards compatability completely since I changed the SettingsModel from int[] to String. The old node would save an int[] with ```addIntArray``` and the new node would try to load a String with ```getString```. I don't know if there is any way to change the SettingsModel without deprecating every single node which uses it.

**Comment by dietzc** [comment]
So we have to deprecate the nodes.

**Comment by seebacherd** [comment]
Created SettingsModelSubsetSelection2 and DialogComponentSubsetSelection2. Every node which used the old settings model and dialog component was deprecated and a new node version was added.

**Comment by dietzc** [comment]
Ok great! can you provide a small test-flow where you demonstrate how to use the image cropper with flow-variables?

**Comment by seebacherd** [comment]
Uploaded a test workflow ("KNIME_testing_subsetselection_flowvariable"). The old image cropper crops from "100-200,50-90,300-500". The new image cropper gets that string as a flow variable input. Both produce the same results.

**Pull request merged**
