### PR TITLE
Add option to read metadata that is not supported by ome-xml

### PR DESCRIPTION
**Pull request by gab1one**
Sprung from the discussion in #96

### CODE REVIEW

**Comment by dietzc** [comment]
Tested with data of @maierl?

**Comment by gab1one** [comment]
Yes it works with @maierl's data, it creates a massive 19k line xml file but that seems to be unavoidable.

**Comment by dietzc** [comment]
Great! Thanks!

**Comment by maierl** [comment]
Thanks from me, too!

**Pull request merged**
