### PR TITLE
Replaces ImgWriter node with a scifio-based reimplementation (ImgSaver)

### PR DESCRIPTION
**Pull request by gab1one**
The new Imgwriter node sports the following features:
- based on scifio
- more options in the node settings
    - custom file name prefix
    - create nonexistent folders  
- various bugfixes

This node requires the still unreleased scifio 0.16 and scifio-ome-xml 0.9.4, to write ome-xml files.

### CODE REVIEW

**Comment by dietzc** [comment]
in the new implementation there shouldn't be any loci.* dependency anymore. Everything should go through io.scif. If not possible, we have to discuss that.

**Comment by dietzc** [comment]
Can you please make sure that the coding guide-lines for "writers" are satisfied?

see: Node Coding Guidelines: page 14
http://tech.knime.org/developers

**Comment by dietzc** [comment]
@gab1one can you update this branch to latest master and check if your test-flows still pass? we are ready to merge I think.

**Comment by gab1one** [comment]
There are still classloader issues at runtime. Do not merge yet.

**Comment by dietzc** [comment]
What exactly?

**Comment by gab1one** [comment]
The ScfioGateway throws the following exception when trying to create a new SCIFIO object.        
``java.lang.IllegalArgumentException: Invalid service: io.scif.ome.services.DefaultOMEMetadataService``
cause:                                                        
``java.lang.NoClassDefFoundError: [Lnet/imagej/axis/AxisType;``

**Comment by dietzc** [comment]
add the imagej-common osgi bundle to the dependencies

**Comment by gab1one** [comment]
That was already set as an dependency. So sadly did not help :(

**Comment by dietzc** [comment]
did you perform an update on your knip-sdk-setup recently (preferably a complete new workspace)?

**Comment by dietzc** [comment]
tested with latest externals update-site: works like a charm! however some remarks

* all parameters should be checked before closing. e.g. if output path was not set, it should be checked before the dialog is closed, not when the node is executed

* The name of the node is rather "Img Writer" than "ImgWriter 2" ;-)

**Comment by gab1one** [comment]
86a1f3b and de84f5a should fix this.

**Comment by dietzc** [comment]
great thanks!

**Comment by maierl** [comment]
When the new image writer should write .ome.tif xyzc images, I get xyzt images instead =/ . tested with the bioformats importer in Fiji

**Comment by gab1one** [comment]
I will look into that asap, could you please send me an example file @maierl ?

**Comment by maierl** [comment]
Thanks @gab1one, you should get an email with a link right away.

**Comment by maierl** [comment]
btw: is there anything that can be done to make the .ome.tiff writer quicker? even with an SSD, it takes ages. If it's of any help, I can provide an example for that, too.

**Comment by gab1one** [comment]
@maierl this seems to be a problem with scifio. I will work with @hinerm to fix this.
About the speed, this is something we are working on together with the scifio team.

**Pull request merged**
