### PR TITLE
Waehlbysplitter fix

### PR DESCRIPTION
**Pull request by tibuch**
Changed seedDistance from squared to non squared.
@Squareys changed as discussed, but review needed.

### CODE REVIEW

**Comment by Squareys** [comment]
Da sind noch sehr viel andere commits von @DanielSeebacher feature-node branch. Die sollten glaub noch nicht auf master.

**Comment by Squareys** [comment]
@dietzc To merge this, a cherry pick of f83134c should be sufficient. I could do this on Friday, if you don't get around to it.

**Comment by dietzc** [comment]
@DanielSeebacher @tibuch please redo this PR, such that only the relevant commit is part of it.

**Comment by Squareys** [comment]
There is no need to close this pull request, we can clean out the branch and keep the PR.

**Pull request closed without merging**
