### PR TITLE
Fix #334

### LINKED ISSUE #334: Image Reader: Drag & Drop of unknown formats
If I drag&drop a strange/unknown format file, e.g. sas7bdat, then the image reader is created on the workbench. this shouldn't happen!

### PR DESCRIPTION
**Pull request by gab1one**
Removes registrations of the image reader to file extensions that are ambiguous.

### CODE REVIEW

**Comment by imagejan** [comment]
How do you decide whether a file extension is "ambiguous"? Some of the removed extensions are quite commonly used file formats, e.g. `lif` from Leica microscopes.

(Anyways, this is just for drag-and-drop and doesn't change the functionality of the Image Reader itself, right?)

**Comment by dietzc** [comment]
good point from @imagejan. Why did you kick `.lif`?

**Comment by dietzc** [comment]
and one more question: if the file extension `.dat` was registered from drag & drop, why did this also work for something .*dat? where is the `string.endsWith(...)` part? On our side?

**Comment by gab1one** [comment]
I looked if I could find them on this list: https://en.wikipedia.org/wiki/List_of_filename_extensions
if I could and there where non image formats with the same extension I removed them. 
I think ``lif`` can come back in though, as the only result I got from the wikipedia page is "Archive" without any more information.

**Comment by gab1one** [comment]
> and one more question: if the file extension .dat was registered from drag & drop, why did this also work for something .*dat? where is the string.endsWith(...) part? On our side?

We only use the  official KNIME extension point ``org.knime.workbench.repository.registeredFileExtensions`` so the ``string.endsWith(..)`` is part of KNIME's  implementation. We only declare the file extension in the ``plugin.xml``

**Comment by dietzc** [comment]
thanks @gab1one

**Comment by imagejan** [comment]
In terms of user experience, IMHO the best solution would be if all extensions remain registered, but KNIME would allow to choose how to handle a dragged file *if* multiple plugins registered the same extension.

**Comment by dietzc** [comment]
@imagejan you are right. I will suggest that. thanks for the feedback.

and also thanks @gab1one for fixing this!

**Pull request merged**
