### PR TITLE
read tiffs from ops.epo.org

### PR DESCRIPTION
**Pull request by DanielSeebacher**
use java advanded imaging codecs to read tiff files from ops.epo.org

### CODE REVIEW

**Comment by dietzc** [comment]
@DanielSeebacher thanks for taking care about this. Unfortunately, I think this PR is  premature and needs more polishment:

* with the new build system we don't add .jar files anymore to our project. it would be adder to add any dependency to https://github.com/knime-ip/knip-externals. 

* If you put such a high priority on this tiff reader, what will happen to the default tiff-reader which can read way more files than the JAI version added in this PR? SCIFIO will always try to use this reader first, which is definitely not what we want. Anyway, the desired behaviour would be, that only if the standard tiff reader fails (because of codecs etc), the jai reader is used. @hinerm is this possible?

**Comment by hinerm** [comment]
@dietzc To keep this as its own reader the options are:
1. Keep the priority high but update the `Checker` so that this only matches images that are certainly JAI TIFFs.
2. Set the priority low and update the other TIFF formats so that they do not attempt to read JAI TIFFs.

However if this is just a matter of codec support... we have a [CodecService](https://github.com/scifio/scifio/blob/scifio-0.21.1/src/main/java/io/scif/codec/CodecService.java) - so it would be ideal if you could just add a JAICodec plugin modeled after [sample codec plugins here](https://github.com/scifio/scifio/tree/scifio-0.21.1/src/main/java/io/scif/codec) so that the SCIFIO TIFFFormat just worked.

Also note that there is an issue to [improve checker logic](https://github.com/scifio/scifio/issues/39) which could help in this scenario (with a multi-stage checking phase where e.g. first the extension is matched, then all the TIFF formats have to read some bytes to decide which TIFF flavor should be used)

Further, a [TIFFService](https://github.com/scifio/scifio/issues/7) could help in this particular case.

**Comment by dietzc** [comment]
Now I'm puzzled. Which of the suggested solutions / hints should we follow? It's actually jiust a codec problem, so we should implement a codec plugin? Actually this should be a PR to SCIFIO then, right?

**Comment by hinerm** [comment]
The solution is up to you and @DanielSeebacher . I assume adding a new codec is sufficient but I know nothing of JAI TIFFs so it's just speculation. My preference would be that you try the codec implementation since it would help reinforce that API... but if you already have a Format that works, it may be faster to just use it (with the caveats regarding checker behavior + priority that I previously mentioned).

Since codecs are plugins you can still ship it with KNIP, but contributing it to SCIFIO would be fantastic!

**Pull request closed without merging**
